changelog:
  exclude:
    authors: ["dependabot[bot]", "github-actions[bot]"]
  categories:
    - title: Breaking
      labels: [breaking]
    - title: Added
      labels: [enhancement, feature]
    - title: Fixed
      labels: [bug]
    - title: Everything else
      labels: ["*"]
