import { createHash } from "node:crypto";
import type { Params, RepoReport } from "./analyse.js";

export interface Report {
  tool: "workproof";
  version: string;
  generatedAt: string;
  params: Params;
  repositories: RepoReport[];
  /** sha256 of the canonical JSON of { params, repositories }. */
  hash: string;
}

const canonical = (v: unknown): string =>
  JSON.stringify(v, (_k, val) =>
    val && typeof val === "object" && !Array.isArray(val)
      ? Object.fromEntries(Object.keys(val).sort().map((k) => [k, (val as Record<string, unknown>)[k]]))
      : val,
  );

/** Without --emails, an author given as an email address is not echoed into the report. */
function publicParams(params: Params): Params {
  if (params.emails || !params.author) return params;
  return { ...params, author: params.author.map((a) => (a.includes("@") ? "(email hidden)" : a)) };
}

export function buildReport(repositories: RepoReport[], params: Params, meta: { version: string; generatedAt: string }): Report {
  const shown = publicParams(params);
  const hash = createHash("sha256").update(canonical({ params: shown, repositories })).digest("hex");
  return { tool: "workproof", version: meta.version, generatedAt: meta.generatedAt, params: shown, repositories, hash };
}

const pct = (x: number) => `${(x * 100).toFixed(1)}%`;
const n = (x: number) => x.toLocaleString("en-US");

function figureLines(f: RepoReport["figures"][number]): string[] {
  const v = f.value;
  switch (f.id) {
    case "tenure":
      return [`${v.first} to ${v.last} (${n(v.days)} days)`];
    case "commitShare":
      return [`${n(v.author)} of ${n(v.total)} non-merge commits, ${pct(v.share)}`];
    case "cadence":
      return [
        `${v.activeWeeks} active weeks of ${v.weeksInTenure}, ${v.commitsPerActiveWeek} commits per active week, longest streak ${v.longestStreakWeeks} weeks`,
        `${v.authorTags} of ${v.tagsInTenure} release tags in tenure`,
      ];
    case "footprint": {
      const hidden = v.ownedDirectories.length > 0 && String(v.ownedDirectories[0].path).startsWith("(hidden");
      return [
        `${n(v.filesTouched)} files touched`,
        `${v.ownedDirectories.length} directories with a commit share at or above the threshold${hidden ? " (paths hidden; run with --paths)" : ""}`,
        ...(hidden ? [] : v.ownedDirectories.slice(0, 12).map((d: { path: string; author: number; total: number; share: number }) => `  ${d.path}: ${d.author} of ${d.total} commits, ${pct(d.share)}`)),
        "languages by lines added: " + (v.languages.length ? v.languages.map((l: { language: string; share: number }) => `${l.language} ${pct(l.share)}`).join(", ") : "none recognised"),
      ];
    }
    case "testsAndDocs":
      return [`${n(v.testChangesAuthor)} of ${n(v.testChangesTotal)} test-file changes, ${pct(v.testShare)}`, `${n(v.docsAuthored)} documents authored`];
    case "survivingLines":
      return [`${n(v.lines)} of ${n(v.linesAttributed)} surviving lines, ${pct(v.share)} (files ${v.filesSampled}/${v.filesTotal}, sample 1 in ${v.sample})`];
    default:
      return [JSON.stringify(v)];
  }
}

export function renderMarkdown(report: Report, narrative?: string): string {
  const out: string[] = [
    `# Engineering report`,
    ``,
    `Generated by workproof ${report.version} on ${report.generatedAt}. Every figure below names the command that produced it and what it cannot show. Verify with \`npx workproof verify <this report>.json\` in the same repository.`,
    ``,
  ];
  for (const repo of report.repositories) {
    out.push(
      `## ${repo.name}`,
      ``,
      `HEAD \`${repo.head.slice(0, 12)}\` · fingerprint \`${repo.fingerprint.slice(0, 16)}\` · identities: ${repo.identity.names.join(", ")}${repo.identity.emails.length ? ` (${repo.identity.emails.join(", ")})` : ""}`,
      ``,
    );
    for (const f of repo.figures) {
      out.push(`### ${f.title}`, ``);
      for (const line of figureLines(f)) out.push(line.startsWith("  ") ? `- ${line.trim()}` : line);
      out.push(``, `How: \`${f.command}\``, ``, `What this cannot show: ${f.limits.join(" ")}`, ``);
    }
  }
  out.push(
    `## Integrity`,
    ``,
    `Report hash \`${report.hash}\` (sha256 of parameters and figures). Repository fingerprints are hashes of the root commit and remote; they identify a repository without naming it.`,
    ``,
  );
  if (narrative) {
    out.push(`## Generated narrative (not verified)`, ``, `The paragraph below was produced by a language model from the figures above and is not part of the hash.`, ``, narrative.trim(), ``);
  }
  return out.join("\n");
}
